openapi: 3.0.3
info:
  title: STD23049 - TD2
  version: '1.0.2'
servers:
  - url: https://localhost.std23049.com
paths:
  /customers:
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Customer'
        required: true
      responses:
        200:
          description: List of updated customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    patch:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PartialCustomer'
        required: true
      responses:
        200:
          description: List of partially updated customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer
    PartialCustomer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer
localhost.std23049.com
